LingChen.NETCore.ClientInformationSystem/ClientInformationMVC/Controllers/ClientController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ClientInformationMVC.Controllers
{
    public class ClientController : Controller
    {
        private readonly IClientService _clientService;

        public ClientController(IClientService clientService)
        {
            _clientService = clientService;
        }
        [HttpGet]
        public IActionResult AddClient()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddClient(ClientRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await _clientService.AddClient(model);

            return RedirectToAction("AddClient");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            var client = await _clientService.GetClientById(id);

            return View(client);
        }

        [HttpPost]
        public async Task<IActionResult> Update(ClientRequestModel model)
        {

            var client = await _clientService.UpdateClient(model);
            Console.WriteLine(client);

            return LocalRedirect("~/");
        }

      

        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {

            var result = await _clientService.DeleteClient(id);
            Console.WriteLine(result);

            return LocalRedirect("~/");
        }
    }
}

LingChen.NETCore.ClientInformationSystem/ClientInformationMVC/Controllers/EmployeeController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Data;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ClientInformationMVC.Controllers
{
    public class EmployeeController : Controller
    {
        private readonly IEmployeesService _employeesService;
    
        public EmployeeController(IEmployeesService employeesService)
        {
            _employeesService = employeesService;
        }
        [HttpGet]
        public IActionResult AddEmployee()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> AddEmployee(EmployeeRequestModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            await _employeesService.AddEmployee(model);

            return RedirectToAction("AddEmployee");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            var employee = await _employeesService.GetEmployeeById(id);

            return View(employee);
        }

        [HttpPost]
        public async Task<IActionResult> Update(EmployeeUpdateModel employeeUpdateModel)
        {

            var employee = await _employeesService.UpdateEmployee(employeeUpdateModel);
  
            return LocalRedirect("~/");
        }



        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {

            var result = await _employeesService.DeleteEmployee(id);
            Console.WriteLine(result);

            return LocalRedirect("~/");
        }

    }
}

LingChen.NETCore.ClientInformationSystem/ClientInformationMVC/Controllers/HomeController.cs
using ClientInformationMVC.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using ApplicationCore.ServiceInterfaces;
using ApplicationCore.Models;

namespace ClientInformationMVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly IEmployeesService _employeesService;
        public HomeController(IEmployeesService employeesService)
        {
            _employeesService = employeesService;
        }

        [HttpGet]
        public async Task<IActionResult> Index()
        {
            var homepageDetails = await _employeesService.GetAllEmployeesClients();
            return View(homepageDetails);
        }


        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

LingChen.NETCore.ClientInformationSystem/ClientInformationMVC/Controllers/InteractionController.cs
using ApplicationCore.Models;
using ApplicationCore.ServiceInterfaces;
using Infrastructure.Data;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;


namespace ClientInformationMVC.Controllers
{
    public class InteractionController : Controller
    {
        private readonly IInteractionsService _interactionsService;

        public InteractionController(IInteractionsService interactionsService)
        {
            _interactionsService = interactionsService;
        }
        [HttpGet]
        public async Task<IActionResult> AddInteraction()
        {
            var interaction = await _interactionsService.AddEmpsClients()
;            return View(interaction);
        }

        [HttpPost]
        public async Task<IActionResult> AddInteraction(InteractionResponseModel model)
        {
            var x = model;
            if (!ModelState.IsValid)
            {
                return View();
            }

            var interaction = await _interactionsService.AddInterations(model);

            Console.WriteLine(interaction);

            return RedirectToAction("AddInteraction");
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {

            var interaction = await _interactionsService.GetInterationById(id);

            return View(interaction);
        }

        //[HttpGet]
        //public async Task<IActionResult> EditByEmp(int id)
        //{

        //    var interaction = await _interactionsService.GetInteractionsByEmployeeId(id);

        //    return View(interaction);
        //}

        [HttpPost]
        public async Task<IActionResult> Update(InteractionResponseModel model)
        {

            var client = await _interactionsService.UpdateInteraction(model);
            Console.WriteLine(client);

            return LocalRedirect("~/");
        }



        [HttpPost]
        public async Task<IActionResult> Delete(int id)
        {

            var result = await _interactionsService.DeleteInteraction(id);
            Console.WriteLine(result);

            return LocalRedirect("~/");
        }

        [HttpGet]
        public async Task<IActionResult> EmployeeInteraction(int id)
        {

            var interaction = await _interactionsService.GetInteractionsByEmployeeId(id);

            return View(interaction);
        }


        [HttpGet]
        public async Task<IActionResult> ClientInteraction(int id)
        {

            var interaction = await _interactionsService.GetInteractionsByClientId(id);

            return View(interaction);
        }


    }
}

LingChen.NETCore.ClientInformationSystem/ClientInformationMVC/Views/Home/Index.cshtml
@model ApplicationCore.Models.HomepageDetailsModel

@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
   

    <div class="btn-group float-left mb-3"  role="group" aria-label="Basic example">
        <a class="btn btn-info" asp-controller="Employee" asp-action="AddEmployee"> Add Employee </a>
        <a class="btn btn-info" asp-controller="Client" asp-action="AddClient"> Add Client </a>
        <a class="btn btn-info" asp-controller="Interaction" asp-action="AddInteraction"> Add Interations </a>
    </div>
    


    @*@foreach (var employee in @Model.Employees)
        {

            <div class="row mt-5">

                <form method="post" asp-controller="Employee" asp-action="delete" asp-route-id="@employee.Id">
                    <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                        Delete
                    </button>
                </form>

                <form method="get" asp-controller="Employee" asp-action="edit" asp-route-id="@employee.Id">
                    <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                        Update
                    </button>
                </form>

                <a asp-controller="Interaction" asp-action="EmployeeInteraction" asp-route-id="@employee.Id">
                    @employee.Name
                </a>

                <div>@employee.Designation</div>
            </div>

        }*@

  
    <table class="table table-bordered table-responsive-md">
        <thead>
            <tr class="table-info text-uppercase text-dark">
                <th scope="colgroup">Employee Name</th>
                <th scope="col">Designation</th>
                <th scope="col" colspan="2">Operation</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var employee in @Model.Employees)
            {
            <tr>
                

                <td>
                    <a asp-controller="Interaction" asp-action="EmployeeInteraction" asp-route-id="@employee.Id">
                        @employee.Name
                    </a>
                </td>
                <td>
                    <p>@employee.Designation</p>
                </td>
                <td>
                    <form method="post" asp-controller="Employee" asp-action="delete" asp-route-id="@employee.Id">
                        <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                            Delete
                        </button>
                    </form>
                </td>
                <td>
                    <form method="get" asp-controller="Employee" asp-action="edit" asp-route-id="@employee.Id">
                        <button type="submit" class="btn btn-sm btn-primary d-none d-md-inline-block">
                            Update
                        </button>
                    </form>
                </td>
            </tr>
            }
        </tbody>
    </table>


    <table class="table table-bordered table-responsive-md mt-4">
        <thead>
            <tr class="table-warning text-uppercase text-dark ">
                <th scope="colgroup">Client Name</th>
                <th scope="col">Email</th>
                <th scope="col">Address</th>
                <th scope="col">Phone Number</th>
                <th scope="col" colspan="2">Operation</th>

            </tr>
        </thead>
        <tbody>
            @foreach (var client in @Model.Clients)
            {
            <tr>


                <td>
                    <a asp-controller="Interaction" asp-action="ClientInteraction" asp-route-id="@client.Id">
                        @client.Name
                    </a>
                </td>
                <td>
                    <p>@client.Email</p>
                </td>
                <td>
                    <p>@client.Address</p>
                </td>
                <td>
                    <p>@client.Phones</p>
                </td>
                <td>
                    <form method="post" asp-controller="Client" asp-action="delete" asp-route-id="@client.Id">
                        <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                            Delete
                        </button>
                    </form>
                </td>
                <td>
                    <form method="get" asp-controller="Client" asp-action="edit" asp-route-id="@client.Id">
                        <button type="submit" class="btn btn-sm btn-primary d-none d-md-inline-block">
                            Update
                        </button>
                    </form>
                </td>
            </tr>
            }
        </tbody>
    </table>





    @*@foreach (var client in @Model.Clients)
    {

        <div class="row mt-5">

            <form method="post" asp-controller="Client" asp-action="delete" asp-route-id="@client.Id">
                <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                    Delete
                </button>
            </form>

            <form method="get" asp-controller="Client" asp-action="edit" asp-route-id="@client.Id">
                <button type="submit" class="btn btn-sm btn-danger d-none d-md-inline-block">
                    Update
                </button>
            </form>

            <a asp-controller="Interaction" asp-action="ClientInteraction" asp-route-id="@client.Id">
                @client.Name
            </a>

            <div>@client.Email</div>
            <div>@client.Address</div>
            <div>@client.Phones</div>
        </div>

    }*@


</div>